[package]
name = "marketdata"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "marketdata"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arrow = "50.0.0"
parquet = "50.0.0"
chrono = "0.4.33"



